---
abstract: 'Memory-efficient approximate descriptive statistics class.'
author:
  - 'Konstantin S. Uvarin <khedin@gmail.com>'
build_requires:
  Data::Dumper: 0
  FindBin: 0
  Test::Exception: 0
  Test::More: 0
  Test::Number::Delta: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Statistics-Descriptive-LogScale
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  POSIX: 0
version: 0.0509
